// Uncaught Exception (Synchronous code)
process.on('uncaughtException', (err) => {
  console.log('ðŸ’£ Undandled Exception:', err.name);
  console.log(err.message);
  console.log(err.stack);
  process.exit(1);
});

// Unhandled rejections (Promises)
process.on('unhandledRejection', (err) => {
  console.log('ðŸ’£ Undandled Rejection:', err.name);
  console.log(err.message);
  console.log(err.stack);
  process.exit(1);
});

process.on('SIGTERM', () => {
  console.log('ðŸ’£ SIGTERM RECEIVED.');
  console.log('ðŸ’£ Process terminated');
});
